JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk
SPARK_HOME=/opt/spark
JAVA=/usr/lib/jvm/java-1.11.0-openjdk/bin/java
JAVAC=/usr/lib/jvm/java-1.11.0-openjdk/bin/javac
JAVAH=/usr/share/aclocal/ax_prog_javah.m4
JAR=/usr/lib/jvm/java-1.11.0-openjdk/bin/jar
JAVA_LIBS='-L/usr/lib/jvm/java-1.11.0-openjdk/lib/server -ljvm'
JAVA_CPPFLAGS='-I/usr/lib/jvm/java-1.11.0-openjdk/include -I/usr/lib/jvm/java-1.11.0-openjdk/include/linux'
JAVA_LD_LIBRARY_PATH=/usr/lib/jvm/java-1.11.0-openjdk/lib/server
